name: CI and CD for Dev

on:
    push:
        branches: [ main ]
env:
    PROJECT_NAME: realworld-go-echo

jobs:
    unit-test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: 1.22.3
            -   name: Run Unit Test
                run: go test -v ./... -coverprofile=coverage.out

            -   name: Upload coverage
                uses: actions/upload-artifact@v4
                with:
                    name: coverage
                    path: ./coverage.out